%% Z100_Manager.Task_Flow_Discharge - action - Full Text Flowchart
flowchart TD
    Start([Start: Z100_Manager.Task_Flow_Discharge])
    If_1{{"IF PVL.Z100_Config.Task.eTask&amp;lt;&amp;gt; Local_Task THEN"}}
    Then_1["THEN"]
    Stmt_1_237["Local_Task:=PVL.Z100_Config.Task.eTask;"]
    Stmt_1_6791["local_status:=eZ100_Status.Flow_Control_Transfer;"]
    Stmt_1_9742["PVL.Z100_Config.READY:=TRUE;"]
    IfEnd_1[Continue...]
    N22["Burkert.Alarm_Window_Convert(window:=PVL.Z100_Config.Target_Flow,Config:=PVL.s8098[s8098_Mapping.FT_101].PDO.VolumeFlow.Alarm_Config);"]
    SubCall_23["CALL: Evaluate_Flow_Discharge"]
    style SubCall_23 fill:#e1f5fe,stroke:#01579b,stroke-width:2px
    Case_24["CASE PVL.Z100_Config.Status.eStatus OF"]
    CaseOpt_24_0["eZ100_Status.EP101_LSHH201_High_High_Level_Alarm"]
    CaseOpt_24_0_L1["Local_Status:=PVL.Z100_Config.Status.eStatus; PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_1["eZ100_Status.PT101_High_High_Pressure_Alarm"]
    CaseOpt_24_1_L1["Local_Status:=PVL.Z100_Config.Status.eStatus;PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_2["eZ100_Status.PT101_Low_Low_Pressure_Alarm"]
    CaseOpt_24_2_L1["Local_Status:=PVL.Z100_Config.Status.eStatus;;PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_3["eZ100_Status.LSLL101_Pump_Intakes_Dry"]
    CaseOpt_24_3_L1["Local_Status:=PVL.Z100_Config.Status.eStatus;PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_4["eZ100_Status.FT101_Low_Low_Flow_Alarm"]
    CaseOpt_24_4_L1["Local_Status:=PVL.Z100_Config.Status.eStatus;PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_5["eZ100_Status.LT101_High_High_Alarm"]
    CaseOpt_24_5_L1["PVL.Z100_Config.READY:=FALSE;"]
    CaseOpt_24_5_L2["IF PVl.AIT[ait_mapping.LT_101_P].Status.eStatus=Burkert.eSensor_Status.HiHi_Alarm THEN"]
    CaseOpt_24_6["Local_Status"]
    CaseOpt_24_6_L1["=PVL.Z100_Config.Status.eStatus;"]
    CaseOpt_24_6_L2["ELSE"]
    CaseOpt_24_7["Local_Status"]
    CaseOpt_24_7_L1["=eZ100_Status.Waiting_For_Level_OK_LT101;"]
    CaseOpt_24_7_L2["END_IF"]
    CaseOpt_24_8["eZ100_Status.Waiting_For_Level_OK_LT101"]
    CaseOpt_24_9["PVL.Z100_Config.READY"]
    CaseOpt_24_9_L1["=FALSE;"]
    CaseOpt_24_10["IF PVl.AIT[ait_mapping.LT_101_P].Status.eStatus=Burkert.eSensor_Status.OK	THEN local_Task"]
    CaseOpt_24_10_L1["=99; END_IF;"]
    CaseOpt_24_11["eZ100_Status.Flow_Control_Transfer"]
    CaseOpt_24_11_L1["PVL.Z100_Config.READY:=TRUE;"]
    CaseEnd_24[Continue...]
    Start --> If_1
    If_1 -- Yes --> Then_1
    Then_1 --> Stmt_1_237
    Stmt_1_237 --> Stmt_1_6791
    Stmt_1_6791 --> Stmt_1_9742
    Stmt_1_9742 --> IfEnd_1
    IfEnd_1 --> N22
    N22 --> SubCall_23
    SubCall_23 --> Case_24
    Case_24 --> CaseOpt_24_0
    CaseOpt_24_0 --> CaseOpt_24_0_L1
    Case_24 --> CaseOpt_24_1
    CaseOpt_24_1 --> CaseOpt_24_1_L1
    Case_24 --> CaseOpt_24_2
    CaseOpt_24_2 --> CaseOpt_24_2_L1
    Case_24 --> CaseOpt_24_3
    CaseOpt_24_3 --> CaseOpt_24_3_L1
    Case_24 --> CaseOpt_24_4
    CaseOpt_24_4 --> CaseOpt_24_4_L1
    Case_24 --> CaseOpt_24_5
    CaseOpt_24_5 --> CaseOpt_24_5_L1
    CaseOpt_24_5_L1 --> CaseOpt_24_5_L2
    Case_24 --> CaseOpt_24_6
    CaseOpt_24_6 --> CaseOpt_24_6_L1
    CaseOpt_24_6_L1 --> CaseOpt_24_6_L2
    Case_24 --> CaseOpt_24_7
    CaseOpt_24_7 --> CaseOpt_24_7_L1
    CaseOpt_24_7_L1 --> CaseOpt_24_7_L2
    Case_24 --> CaseOpt_24_8
    Case_24 --> CaseOpt_24_9
    CaseOpt_24_9 --> CaseOpt_24_9_L1
    Case_24 --> CaseOpt_24_10
    CaseOpt_24_10 --> CaseOpt_24_10_L1
    Case_24 --> CaseOpt_24_11
    CaseOpt_24_11 --> CaseOpt_24_11_L1
    CaseOpt_24_0_L1 --> CaseEnd_24
    CaseOpt_24_1_L1 --> CaseEnd_24
    CaseOpt_24_2_L1 --> CaseEnd_24
    CaseOpt_24_3_L1 --> CaseEnd_24
    CaseOpt_24_4_L1 --> CaseEnd_24
    CaseOpt_24_5_L2 --> CaseEnd_24
    CaseOpt_24_6_L2 --> CaseEnd_24
    CaseOpt_24_7_L2 --> CaseEnd_24
    CaseOpt_24_8 --> CaseEnd_24
    CaseOpt_24_9_L1 --> CaseEnd_24
    CaseOpt_24_10_L1 --> CaseEnd_24
    CaseOpt_24_11_L1 --> CaseEnd_24
    End([End])
    CaseOpt_24_11_L1 --> End
